name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [ '28.2', '29.1' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emacs ${{ matrix.emacs_version }}
        uses: purcell/setup-emacs@v7.0
        with:
          version: ${{ matrix.emacs_version }}

      - name: Byte-compile
        run: emacs -Q --batch -L . -f batch-byte-compile *.el

      - name: Run ERT tests
        run: emacs -Q --batch -L . -l codex-cli.el -l tests/codex-cli-test.el -f ert-run-tests-batch-and-exit
