name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Emacs
        run: sudo apt-get update && sudo apt-get install -y emacs-nox
      - name: Byte-compile
        run: emacs -Q --batch -L . -f batch-byte-compile *.el
      - name: Run ERT
        run: |
          emacs -Q --batch \
            -L . \
            -l codex-cli.el \
            -l tests/codex-cli-test.el \
            -f ert-run-tests-batch-and-exit
