name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [ '28.2', '29.1' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emacs ${{ matrix.emacs_version }}
        uses: purcell/setup-emacs@v7
        with:
          version: ${{ matrix.emacs_version }}

      - name: Setup Eask
        uses: emacs-eask/setup-eask@v2

      - name: Install dependencies
        run: eask install

      - name: Byte-compile
        run: eask compile

      - name: Run ERT tests
        run: eask test ert tests/*.el

      - name: Lint (checkdoc + package-lint)
        run: eask lint checkdoc && eask lint package-lint
